# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         AIX-LVM
version:      1.0
version_from: lib/AIX/LVM.pm
installdirs:  site
requires:
    IO::Handle:                    1.0
    IO::Select:                    1.0
    IPC::Open3:                    1.0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
